apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: denyslins/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.js"
            src: .
    - image: denyslins/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "*.js"
            src: .
    - image: denyslins/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "*.js"
            src: .
    - image: denyslins/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "*.js"
            src: .
    - image: denyslins/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "*.js"
            src: .
    - image: denyslins/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "*.js"
            src: .
